export const TEAM_ROLE = {
  PLAYER: 'PLAYER',
  TEAM_MANAGER: 'TEAM_MANAGER',
  HEAD_COACH: 'HEAD_COACH',
  TRAINER: 'TRAINER',
  ASSISTANT_COACH: 'ASSISTANT_COACH',
}

export const POSITION_ROLE = {
  WING_SPIKER: 'WING_SPIKER',
  OUTSIDE_HITTER: 'OUTSIDE_HITTER',
  OPPOSITE_HITTER: 'OPPOSITE_HITTER',
  MIDDLE_BLOCKER: 'MIDDLE_BLOCKER',
  SETTER: 'SETTER',
  LIBERO: 'LIBERO',
  DEFENSIVE_SPECIALISTS: 'DEFENSIVE_SPECIALISTS',
  SERVING_SPECIALIST: 'SERVING_SPECIALIST',
}

export const SITE_ROLE = {
  PLAYER: 'PLAYER',
  ADMIN: 'ADMIN',
  USER: 'USER',
  SUPERADMIN: 'SUPERADMIN',
}
